version: "2.1"
volumes: 
  logger-pgdata:
    driver: local
services:
  log-test-core:
    container_name: log-test-core
    image: chipin/core
    volumes:
      - /var/cilogger/c:/usr/share/nginx/html/c
    ports:
      - "81:81"
    privileged: true
    hostname: test-core.chip-in.net
  postgresql:
    container_name: log-postgres-container
    build: ./postgres/
    restart: always
    volumes:
      - logger-pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  log-aggregate-webserver:
    container_name: log-aggregate-webserver
    image: chipin/log-aggregate-server:latest
    working_dir: /usr/local/chip-in/log-aggregate-server/server/
    tty: true
    ports:
      - "3001:3001"
    command: ["npm", "start"]
    environment:
      APP_PORT: 3001
#     LOGGER_LOGLEVEL: warn
#     LOGGER_MAX_STRING_LENGTH: 1024
#     LOG_LANGUAGE: "ja-JP,en-US"
      DB_USER: chipinadmin
      DB_HOST: postgresql
      DB_DATABASE: logdb
#     DB_PASSWORD: your.password.secure
      DB_PORT: 5432
    links:
      - log-test-core
      - postgresql
